export const actionTypes = {
    CHANGE_CITY: 'CHANGE_CITY',
    FORECAST: 'FORECAST',
    CURRENT: 'CURRENT',
    CHANGE_WEATHER_SERVICE: 'CHANGE_WEATHER_SERVICE',
    USER_EVENTS: 'USER_EVENTS',
};
